### ISSUE TITLE
Is it possible to add an image to a cell ?

### ISSUE THREAD

**Issue by jeremyhalin** [heksemann/HexPDF#1]
Hi, I'm using your library which is great.
I want to create a two columns table.
The first column will be "LAST NAME First Name" and will contain text only.
The second colmun will contain an image.

Is it possible ?
Thanks.

**Comment by jeremyhalin** [comment]
Alright, just found `addCell(float x, float y, float w, BufferedImage image, int flags)``
I will try this.

**Comment by heksemann** [comment]
Dear HJerem,
sorry for lacking response - I´ve been too busy lately to follow up HexPDF.
Luckily you found the solution yourself (y)

**Comment by jeremyhalin** [comment]
No problem.
